package consts

var (
	DEVELOPMENT             = "DEVELOPMENT"
	LOG_LEVEL               = "LOG_LEVEL"
	LOG_JSON                = "LOG_JSON"
	LOG_ADD_CALLER          = "LOG_ADD_CALLER"
	LOG_DISABLE_STACKTRACE  = "LOG_DISABLE_STACKTRACE"
	LOG_UNESCAPED_MULTILINE = "LOG_UNESCAPED_MULTILINE"
	LOG_COLORIZE_LINE       = "LOG_COLORIZE_LINE"

	// Azure related environment variables
	AZURE_SUBSCRIPTION_ID       = "AZURE_SUBSCRIPTION_ID"
	AZURE_OBJECT_ID             = "AZURE_OBJECT_ID"
	AZURE_CLIENT_SECRET         = "AZURE_CLIENT_SECRET" // #nosec G101 -- not a credential, just env var name
	AZURE_VALIDATE_CONNECTIVITY = "AZURE_VALIDATE_CONNECTIVITY"
	AZURE_DEFAULT_LOCATION      = "AZURE_DEFAULT_LOCATION"

	// Vitistack related constants
	VITISTACK_NAME             = "VITISTACK_NAME"
	NAME_KUBERNETES_PROVIDER   = "NAME_KUBERNETES_PROVIDER"
	TENANT_CONFIGMAP_NAME      = "TENANT_CONFIGMAP_NAME"
	TENANT_CONFIGMAP_NAMESPACE = "TENANT_CONFIGMAP_NAMESPACE"
	TENANT_CONFIGMAP_DATA_KEY  = "TENANT_CONFIGMAP_DATA_KEY"
	DEFAULT_KUBERNETES_VERSION = "DEFAULT_KUBERNETES_VERSION"
)
